openapi: 3.0.1
info:
  title: Quiz Master API
  description: Dokumentasi API untuk Website Quiz Master mencakup Autentikasi dan Manajemen Profil.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: https://api.quizmaster.com/api/v1
    description: Production server

tags:
  - name: "Auth"
    description: Operasi seputar Autentikasi (Register & Login)
  - name: "Profiles"
    description: Operasi seputar Profil User

paths:
  # --- AUTHENTICATION ---
  /auth/register:
    post:
      tags:
        - "Auth"
      summary: Registrasi user baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, email, password, confirmPassword]
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        201:
          description: User berhasil dibuat
        400:
          description: Validasi gagal atau password tidak cocok

  /auth/login:
    post:
      tags:
        - "Auth"
      summary: Login user manual
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login berhasil, mengembalikan token
        401:
          description: Kredensial salah

  /auth/google:
    get:
      tags:
        - "Auth"
      summary: Redirect ke Google OAuth2
      responses:
        302:
          description: Mengarahkan ke halaman login Google

  # --- PROFILES ---
  /profiles/detail:
    get:
      tags:
        - "Profiles"
      summary: Mendapatkan detail profil user yang sedang login
      security:
        - bearerAuth: []
      responses:
        200:
          description: Detail profil berhasil diambil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

  /profiles/update:
    put:
      tags:
        - "Profiles"
      summary: Update data profil dan avatar
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                city:
                  type: string
                birth_date:
                  type: string
                  format: date
                avatar_url:
                  type: string
                  format: binary
      responses:
        200:
          description: Profil berhasil diperbarui

  /profiles/update-password:
    put:
      tags:
        - "Profiles"
      summary: Mengubah password user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [oldPassword, newPassword, newPasswordConfirmation]
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
                newPasswordConfirmation:
                  type: string
      responses:
        200:
          description: Password berhasil diubah
        400:
          description: Password lama salah atau konfirmasi tidak cocok

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        fullname:
          type: string
        email:
          type: string
        google_id:
          type: string
          nullable: true
        profile:
          $ref: '#/components/schemas/Profile'
    Profile:
      type: object
      properties:
        id:
          type: integer
        avatar_url:
          type: string
          nullable: true
        birth_date:
          type: string
          format: date
        city:
          type: string