openapi: 3.0.1
info:
  title: Quiz Master API
  description: Dokumentasi API untuk Website Quiz Master mencakup Autentikasi dan Manajemen Profil.
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1
    description: Local server
  - url: https://simple-quiz-app-be.vercel.app/api/v1
    description: Production server

tags:
  - name: "Auth"
    description: Operasi seputar Autentikasi
  - name: "Profiles"
    description: Operasi seputar Profil User

paths:
  # --- AUTHENTICATION ---
  /auth/register:
    post:
      tags:
        - "Auth"
      summary: Registrasi user baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, email, password, confirmPassword]
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                confirmPassword:
                  type: string
      responses:
        201:
          description: User berhasil dibuat
        400:
          description: Validasi gagal

  /auth/login:
    post:
      tags:
        - "Auth"
      summary: Login user manual
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: Login berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      token:
                        type: string
        401:
          description: Kredensial salah

  /auth/me:
    get:
      tags:
        - "Auth"
      summary: Authenticate current user
      description: Mendapatkan data profil user yang sedang login menggunakan token.
      security:
        - bearerAuth: []
      responses:
        200:
          description: Berhasil mendapatkan data user
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "OK"
                  data:
                    $ref: "#/components/schemas/User"
        403:
          description: Token tidak valid atau tidak disediakan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: User tidak ditemukan
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/google:
    get:
      tags:
        - "Auth"
      summary: Redirect ke Google OAuth2
      responses:
        302:
          description: Mengarahkan ke halaman login Google

  # --- PROFILES ---
  /profiles/detail:
    get:
      tags:
        - "Profiles"
      summary: Mendapatkan detail profil (sama dengan authenticate)
      security:
        - bearerAuth: []
      responses:
        200:
          description: Sukses
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'

  /profiles/update:
    put:
      tags:
        - "Profiles"
      summary: Update data profil dan avatar
      security:
        - bearerAuth: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                fullname:
                  type: string
                city:
                  type: string
                birth_date:
                  type: string
                  format: date
                  example: "1990-01-01"
                avatar_url:
                  type: string
                  format: binary
      responses:
        200:
          description: Profil berhasil diperbarui
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                  data:
                    $ref: '#/components/schemas/User'

  /profiles/update-password:
    put:
      tags:
        - "Profiles"
      summary: Mengubah password user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [oldPassword, newPassword, newPasswordConfirmation]
              properties:
                oldPassword:
                  type: string
                newPassword:
                  type: string
                newPasswordConfirmation:
                  type: string
      responses:
        200:
          description: Password berhasil diubah
        400:
          description: Password lama salah atau konfirmasi tidak cocok

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      properties:
        status:
          type: boolean
          example: false
        message:
          type: string
        data:
          type: object
          nullable: true
          example: null
          
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        fullname:
          type: string
          example: "Budi Setiadi"
        email:
          type: string
          example: "budi@gmail.com"
        google_id:
          type: string
          nullable: true
        profile:
          $ref: '#/components/schemas/Profile'

    Profile:
      type: object
      properties:
        id:
          type: integer
          example: 10
        avatar_url:
          type: string
          nullable: true
          example: "https://ik.imagekit.io/your_id/avatar.png"
        birth_date:
          type: string
          example: "1995-05-20"
        city:
          type: string
          example: "Jakarta"